#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : i3blocks
Version  : 1.5
Release  : 5
URL      : https://github.com/vivien/i3blocks/archive/1.5/i3blocks-1.5.tar.gz
Source0  : https://github.com/vivien/i3blocks/archive/1.5/i3blocks-1.5.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-3.0
Requires: i3blocks-bin = %{version}-%{release}
Requires: i3blocks-data = %{version}-%{release}
Requires: i3blocks-license = %{version}-%{release}
Requires: i3blocks-man = %{version}-%{release}
BuildRequires : pkgconfig(bash-completion)

%description
:progname: i3blocks
:toc:
= {progname}
A feed generator for text based status bars

%package bin
Summary: bin components for the i3blocks package.
Group: Binaries
Requires: i3blocks-data = %{version}-%{release}
Requires: i3blocks-license = %{version}-%{release}

%description bin
bin components for the i3blocks package.


%package data
Summary: data components for the i3blocks package.
Group: Data

%description data
data components for the i3blocks package.


%package license
Summary: license components for the i3blocks package.
Group: Default

%description license
license components for the i3blocks package.


%package man
Summary: man components for the i3blocks package.
Group: Default

%description man
man components for the i3blocks package.


%prep
%setup -q -n i3blocks-1.5
cd %{_builddir}/i3blocks-1.5

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1579287109
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
%autogen --disable-static
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1579287109
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/i3blocks
cp %{_builddir}/i3blocks-1.5/COPYING %{buildroot}/usr/share/package-licenses/i3blocks/8624bcdae55baeef00cd11d5dfcfa60f68710a02
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/i3blocks

%files data
%defattr(-,root,root,-)
/usr/share/bash-completion/completions/i3blocks

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/i3blocks/8624bcdae55baeef00cd11d5dfcfa60f68710a02

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/i3blocks.1
